version: '3.8'

services:
  bookcatalog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - ./data:/app/data
    depends_on:
      - database
    networks:
      - bookcatalog-network

  database:
    image: "alpine/h2:latest"
    container_name: h2-database
    volumes:
      - ./data:/opt/h2-data
    ports:
      - "1521:1521"
    command: ["-ifNotExists", "-baseDir", "/opt/h2-data"]
    networks:
      - bookcatalog-network

networks:
  bookcatalog-network:
    driver: bridge
